#! /usr/bin/env bash

# Define os diretórios
export DOTFILES=$HOME/.config/dotfiles
export SCRIPTS=$DOTFILES/scripts
export XDG_HOME_BIN=$HOME/.local/bin
export DOTSHELL=fish

for script in "$DOTFILES"/scripts/*
do

    source "$script"

done

ask_for_sudo "Informe sua senha para iniciar a instalação dos módulos: "

spinner "Iniciando a instalação dos módulos" -- sleep 2

for module in "$DOTFILES"/modules/*/sh
do

    source "$module"

done

success "Instalação concluída"
