#! /usr/bin/env bash

source "$SCRIPTS"/utils
source "$SCRIPTS"/manager

APPS="$DOTFILES/modules/aur/list"
YAY_GIT_DIR="/tmp/yay"

if ! exists yay; 
then

    spinner "Instalando o Yay" -- git clone --quiet https://aur.archlinux.org/yay.git $YAY_GIT_DIR
    cd $YAY_GIT_DIR || exit
    makepkg -si
    cd "$DOTFILES" || exit

fi

spinner "Iniciando a instalação dos pacotes via Yay" -- sleep 1

while IFS=$'\n' read -r package; do

    package=$(echo $package | sed -e "s| ||g")

    spinner "Instalando o $package via Yay" -- yay -Syyu --noconfirm "$package" | tee -a "$DOTFILES"/yay."$package".log

done <"$APPS"
