#! /usr/bin/env bash

source "$SCRIPTS"/utils
source "$SCRIPTS"/manager

APPS="$DOTFILES/modules/aur/list"
YAY_GIT_DIR="/tmp/yay"

if ! exists yay; 
then

    git clone https://aur.archlinux.org/yay.git $YAY_GIT_DIR
    cd yay || exit
    makepkg -si
    cd ..
    rm -rf yay

fi

spinner "Iniciando a instalação dos pacotes via Yay" -- sleep 1

while IFS=$'\n' read -r package; do

    package=$(echo $package | sed -e "s| ||g")

    yay -Syyu --noconfirm "$package"

done <"$APPS"
