#! /usr/bin/env bash

source "$SCRIPTS"/utils
source "$SCRIPTS"/manager

APPS="$DOTFILES/modules/aur/list"

if ! exists yay; 
then

    spinner "Iniciando a instalação do Yay" -- git clone https://aur.archlinux.org/yay.git
    cd yay || exit
    spinner "Instalando o Yay" -- makepkg -si
    cd ..
    rm -rf yay

fi

spinner "Iniciando a instalação dos pacotes via Yay" -- sleep 1

while IFS=$'\n' read -r package; do

    package=$(echo $package | sed -e "s| ||g")

    yay -Syyu --noconfirm "$package"

done <"$APPS"
