#! /usr/bin/env bash

source "$SCRIPTS"/utils
source "$SCRIPTS"/manager

apply() {

    local arq=$1
    local dump=$2
    local config
    
    config=$(basename "$arq" | tr "_" ".")

    if exists dconf &&
       dconf dump "$dump" > /dev/null &&
       dconf load "$dump" < "$arq"
    then

        success "Configuração definida em $config aplicada com sucesso"

    fi

}

convert_conf() {

    echo /"$1"/ | tr "_" "/"

}

info_not_supported() {

    error "Não é possível atribuir os atalhos em ambientes que não estejam rodando o Gnome"

    exit 1

}

test "$(echo "$XDG_CURRENT_DESKTOP" | grep -i "gnome")" || info_not_supported

for conf in "$DOTFILES"/modules/gnome/keybinds/*
do

    path=$(convert_conf "$(basename "$conf")")

    apply "$conf" "$path"

done




