#! /usr/bin/env bash

source "$SCRIPTS"/utils
source "$SCRIPTS"/manager

apply() {

    local arq=$1
    local dump=$2
    
    if exists dconf &&
       dconf dump "$dump" > /dev/null &&
       dconf load "$dump" < "$arq"
    then

        success "Configuração definida em $dump aplicada com sucesso"

    fi

}

convert_conf() {

    echo /"$1"/ | tr "_" "/"

}

if echo "$XDG_CURRENT_DESKTOP" | grep -i "GNOME" > /dev/null 
then

    for conf in "$DOTFILES"/modules/gnome/keybinds/*
    do

        apply "$conf" "$(convert_conf "$(basename "$conf")")"

    done

fi






