#! /usr/bin/env bash

source "$SCRIPTS"/utils
source "$SCRIPTS"/manager

not_exists_as_snap() {

    ! snap list | grep "$1" > /dev/null &&
    ! exists "$1"

}

if exists snap 
then

    spinner "Iniciando a instalação dos pacotes snap" -- sleep 1

    if not_exists_as_snap code &&
       spinner "Instalando o code" -- sudo snap install code --classic
    then

        success "code instalado com sucesso"
    
    elif ! not_exists_as_snap code
    then

        warn "code já instalado"

    else
        
        snap_not_installed=( "code" )

    fi

    if not_exists_as_snap intellij-idea-community &&
       spinner "Instalando o intellij-idea-community" -- sudo snap install intellij-idea-community --classic
    then

        success "intellij-idea-community instalado com sucesso"
    
    elif ! not_exists_as_snap intellij-idea-community
    then

        warn "intellij-idea-community já instalado"

    else

        snap_not_installed=( "intellij-idea-community" )

    fi

    if [ -f "$HOME"/.hidden ] && ! grep "snap" "$HOME"/.hidden > /dev/null || [ ! -f "$HOME"/.hidden ]
    then

        echo "snap" >> "$HOME"/.hidden 

    fi

    if test -z ${snap_not_installed[@]} 
    then

        success "Todos os snaps foram instalados"
        
    fi

fi


