#! /usr/bin/env bash

source "$SCRIPTS"/utils
source "$SCRIPTS"/manager

ARQ=/etc/modprobe.d/hid_apple.conf


if [ ! -f $ARQ ];
then

    info "Iniciando a configuração do teclado"
    echo "options hid_apple fnmode=1" | sudo tee $ARQ > /dev/null &&
    sudo sed -i "s|FILES=()|FILES=($ARQ)|g" /etc/mkinitcpio.conf
    sudo mkinitcpio -P &&
    success "Teclado configurado com sucesso"
  
fi



