#! /usr/bin/env bash

source "$SCRIPTS"/utils
source "$SCRIPTS"/manager

APPS="$DOTFILES/modules/apps/list"

spinner "Iniciando a instalação dos pacotes via Pacman" -- sleep 1

while IFS=$'\n' read -r package; do

    package=$(echo $package | sed -e "s| ||g")

    sudo pacman -Syu --needed -noconfirm "$package"

done <"$APPS"
