#! /usr/bin/env bash

source "$SCRIPTS"/utils
source "$SCRIPTS"/manager

flags="-S --noconfirm --needed"
pac="sudo pacman $flags"
yay="yay $flags"
APPS="$DOTFILES/modules/apps/list"

install() {

    if echo "$1" | grep "AUR" > /dev/null && exists yay
    then

        $yay "${1//AUR/}"

    else

        $pac "$1"

    fi

}

if ! exists yay;
then

    $pac yay
    
fi
    
spinner "Iniciando a instalação dos pacotes" -- sleep 1

while IFS=$'\n' read -r package
do

    if is_not_installed "$package" 
    then

        install "$package"

    elif ! is_not_installed "$package"
    then

        warn "$package já instalado"
    
    else
        
        app_repo_not_installed=( "$package" )

    fi

done < "$APPS"

if test -z "${app_repo_not_installed[@]}" 
then

    success "Aplicativos do repositório foram instalados com sucesso"

else

    for package_not_installed in ${app_repo_not_installed[@]}
    do
        
        warn "$package_not_installed não foi instalado"

    done
    
fi
