#! /usr/bin/env bash

source "$SCRIPTS"/utils
source "$SCRIPTS"/manager

flags="-S --noconfirm --needed"
pacman="sudo pacman $flags"
pamac="pamac build --no-confirm"
APPS="$DOTFILES/modules/apps/list"


install() {

    if echo "$1" | grep "AUR" > /dev/null && exists yay
    then

        spinner "Instalando ${1//AUR/}" -- $pamac "${1//AUR/}" || app_repo_not_installed=( "${1//AUR/}" )

    else

        spinner "Instalando $1" -- $pacman "$1" || app_repo_not_installed=( "$1" )

    fi

}
    
spinner "Iniciando a instalação dos pacotes" -- sleep 1

while IFS=$'\n' read -r package
do

    install "$package"

done < "$APPS"

if test -z "${app_repo_not_installed[@]}" 
then

    success "Aplicativos do repositório foram instalados com sucesso"

else

    for package_not_installed in ${app_repo_not_installed[@]}
    do
        
        warn "$package_not_installed não foi instalado"

    done
    
fi
