#! /usr/bin/env bash

flags="-S --noconfirm --needed"
pac="sudo pacman $flags"

exists() {

    which "$1" > /dev/null

}

install() {

    for package in $@ 
    do

        if ! exists "$package"
        then

            $pac "$package" 

        fi

    done

}

put() {

    local value=$1
    local file=$2

    test -f "$file" || touch "$file"
  
    if ! grep "$value" "$file" > /dev/null
    then

        echo "$value" >> "$file"

    fi

}

test -d "$HOME"/.config/dotfiles && exit

install git github-cli
put "alias clone='gh auth login && gh repo clone lucasvsr/dotfiles $HOME/.config/dotfiles'" "$HOME"/.bash_aliases 
put "alias setup='bash $HOME/.config/dotfiles/init'" "$HOME"/.bash_aliases
put "alias clone='gh auth login && gh repo clone lucasvsr/dotfiles $HOME/.config/dotfiles'" "$HOME"/.zshrc 
put "alias setup='bash $HOME/.config/dotfiles/init'" "$HOME"/.zshrc

if test -f "$HOME"/.bashrc
then

    if grep ".bash_aliases" "$HOME"/.bashrc > /dev/null
    then

        source "$HOME"/.bashrc

    else

        source "$HOME"/.bash_aliases

    fi

fi