#! /usr/bin/env bash

exists() {

    type "$1" > /dev/null

}

install() {

    for package in $@ 
    do

        if ! exists "$package"
        then

            sudo pacman -Syu --needed --noconfirm "$package" 

        fi

    done

}

_gh() {

    if ! exists gh && exists curl
    then

        install github-cli

    fi

}

put() {

    local value=$1
    local file=$2

    test -f "$file" || touch "$file"
  
    if ! grep "$value" "$file" > /dev/null
    then

        echo "$value" >> "$file"

    fi

}

install git
_gh
put "alias clone='gh auth login && gh repo clone lucasvsr/dotfiles $HOME/.config/dotfiles -- --branch feature/arch'" "$HOME"/.bash_aliases 
put "alias setup='bash $HOME/.config/dotfiles/init'" "$HOME"/.bash_aliases

if test -f "$HOME"/.bashrc
then

    if grep ".bash_aliases" "$HOME"/.bashrc > /dev/null
    then

        source "$HOME"/.bashrc

    else

        source "$HOME"/.bash_aliases

    fi

fi