#! /bin/env bash

source "$SCRIPTS"/utils

exists() {

    command -v "$1" > /dev/null

}

exists_in_repo() {

    test "$(nala search $1 2> /dev/null)"

}

is_not_installed() {

    ! pacman -Qe "$1" &> /dev/null

}

is_sync() {

    cat "$DEB_REPO" | grep -w "$1" > /dev/null

}

add_package() {

    if ! is_sync "$1" && exists "$1"; 
    then

        echo "$1" >> "$DEB_REPO"
        sort_file "$DEB_REPO"

    fi

}

remove_package() {

    sed "/$1/d" "$DEB_REPO" >> deb && mv deb "$DEB_REPO"

}

is_git_repo() {

    git rev-parse 2> /dev/null

}

git_current_branch() {

    is_git_repo && git symbolic-ref --short HEAD

}

git_default_branch() {

    if is_git_repo 
    then

        if [ -f .git/refs/heads/"$(git config --get init.defaultBranch)" ]
        then

            git config --get init.defaultBranch

        else

            echo master 

        fi
        
    fi

}

branch_exists() {

    git branch | grep "$1" > /dev/null

}

branch_remote_exists() {

    git fetch --quiet && git branch --all | grep "remotes/origin/$1" > /dev/null

}
