#! /usr/bin/env bash

source "$SCRIPTS"/utils
source "$SCRIPTS"/manager

if ! exists nix
then

    sh <(curl -L https://nixos.org/nix/install) --daemon
    
fi

if test -f /etc/profile.d/nix.sh && 
   source /etc/profile.d/nix.sh && 
   ! exists home-manager
then

    nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
    nix-channel --update

    export NIX_PATH=$HOME/.nix-defexpr/channels:/nix/var/nix/profiles/per-user/root/channels${NIX_PATH:+:$NIX_PATH}

    nix-shell '<home-manager>' -A install

fi

if test -f "$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh" && 
   source "$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh" && 
   exists home-manager 
then

    info "Iniciando a instalação dos pacotes via home-manager (Nix)"
    sleep 1

    if home-manager --file "$DOTFILES"/home.nix switch -b backup &> /dev/null
    then

        success "Pacotes do home-manager instalados e configurados"

    fi
    
fi