#! /usr/bin/env bash

source "$SCRIPTS"/utils
source "$SCRIPTS"/manager

remove_travas() {

    if [ -d "/var/lib/dpkg/lock-frontend" ]; then
        
        info "Removendo travas"
        sudo rm /var/lib/dpkg/lock-frontend &&
        sudo rm /var/cache/apt/archives/lock &&
        success "Travas removidas!"
        
    fi

}

_docker() {

    if ! exists docker && ! test -f /etc/apt/keyrings/docker.gpg; 
    then

        sudo mkdir -p /etc/apt/keyrings &&
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg &&
        echo \
        "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
        $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

        PRECISA_ATUALIZAR=1
        
    fi
    
}

_nala() {

    if ! exists nala
    then

        echo "deb [arch=amd64,arm64,armhf] http://deb.volian.org/volian/ scar main" | sudo tee /etc/apt/sources.list.d/volian-archive-scar-unstable.list > /dev/null
        wget -nv -qO - https://deb.volian.org/volian/scar.key | sudo tee /etc/apt/trusted.gpg.d/volian-archive-scar-unstable.gpg > /dev/null
        
        PRECISA_ATUALIZAR=1

    fi

}

_ulauncher() {

    if ! exists ulauncher
    then

        sudo add-apt-repository ppa:agornostal/ulauncher

        PRECISA_ATUALIZAR=1
        
    fi

}

_vscode() {

    if ! exists code
    then
        
        wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > /tmp/packages.microsoft.gpg
        sudo install -D -o root -g root -m 644 /tmp/packages.microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg
        sudo sh -c 'echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list'

        PRECISA_ATUALIZAR=1

    fi

}

_docker
_nala
_ulauncher
_vscode

if [ -n "$PRECISA_ATUALIZAR" ]
then

    if spinner "Atualizando os pacotes" -- sudo apt update -y -qq
    then
        
        success "Pacotes atualizados"

    fi

    if spinner "Atualizando o sistema" -- sudo apt upgrade -y -qq
    then

        success "Sistema atualizado"

    fi

    remove_travas
    
fi


